import{a as S,S as q,i as u}from"./assets/vendor-Dy2ZTtfi.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const P="51376871-d210e7f13e39905b8a62b8cdf",M="https://pixabay.com/api/";async function f(c,s=1){return(await S.get(M,{params:{key:P,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}})).data}const b=document.querySelector(".gallery"),L=document.querySelector(".loader"),v=document.querySelector(".load-more");let d;function p(c){const s=c.map(({webformatURL:a,largeImageURL:o,tags:e,likes:t,views:l,comments:r,downloads:i})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${o}">
            <img class="gallery-image" src="${a}" alt="${e}" width="360" height="200" />
          </a>
          <ul class="gallery-info">
            <li class="info-block"><p class="label">Likes</p><p class="value">${t}</p></li>
            <li class="info-block"><p class="label">Views</p><p class="value">${l}</p></li>
            <li class="info-block"><p class="label">Comments</p><p class="value">${r}</p></li>
            <li class="info-block"><p class="label">Downloads</p><p class="value">${i}</p></li>
          </ul>
        </li>`).join("");b.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function E(){b.innerHTML=""}function h(){L.classList.remove("is-hidden")}function m(){L.classList.add("is-hidden")}function g(){v.classList.remove("is-hidden")}function y(){v.classList.add("is-hidden")}document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".form"),s=document.querySelector(".load-more");let a="",o=1,e=0;const t=15;c.addEventListener("submit",async function(r){r.preventDefault();const i=r.currentTarget.elements["search-text"];if(i){if(a=i.value.trim(),!a){u.error({message:"Please enter a search query!",position:"topRight"});return}E(),o=1,y(),h();try{const n=await f(a,o);if(e=n.totalHits,n.hits.length===0){u.error({message:"Sorry, there are no images matching your search query.",position:"bottomRight"});return}p(n.hits);const w=Math.ceil(e/t);o<w?g():u.info({message:"You've reached the end of the results.",position:"bottomRight"})}catch{u.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{m(),i.value=""}}}),s.addEventListener("click",async()=>{o++,h(),y();try{const r=await f(a,o);p(r.hits);const i=Math.ceil(e/t);o>=i?u.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}):g(),l()}catch{u.error({message:"Failed to load more images.",position:"topRight"})}finally{m()}});function l(){var n;const r=(n=document.querySelector(".gallery"))==null?void 0:n.firstElementChild;if(!r)return;const{height:i}=r.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
