import{a as q,S as B,i}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="51376871-d210e7f13e39905b8a62b8cdf",P="https://pixabay.com/api/";function f(o,t=1){return q.get(P,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}}).then(s=>s.data)}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more");let u;function g(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:a,comments:w,downloads:S})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${s}" alt="${e}" width="360" height="200" />
          </a>
          <ul class="gallery-info">
            <li class="info-block"><p class="label">Likes</p><p class="value">${r}</p></li>
            <li class="info-block"><p class="label">Views</p><p class="value">${a}</p></li>
            <li class="info-block"><p class="label">Comments</p><p class="value">${w}</p></li>
            <li class="info-block"><p class="label">Downloads</p><p class="value">${S}</p></li>
          </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new B(".gallery a",{captionsData:"alt",captionDelay:250})}function $(){h.innerHTML=""}function y(){p.classList.remove("is-hidden")}function b(){p.classList.add("is-hidden")}function L(){m.classList.remove("is-hidden")}function v(){m.classList.add("is-hidden")}const R=document.querySelector(".form"),x=document.querySelector(".load-more");let c="",l=1,d=0;R.addEventListener("submit",async function(o){if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),!c){i.error({message:"Please enter a search query!",position:"topRight"});return}$(),l=1,v(),y();try{const t=await f(c,l);if(d=t.totalHits,t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query.",position:"bottomRight"});return}g(t.hits),t.hits.length<d&&L()}catch{i.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{b(),o.currentTarget.elements["search-text"].value=""}});x.addEventListener("click",async()=>{l++,y(),v();try{const o=await f(c,l);g(o.hits);const t=Math.ceil(d/15);l>=t?i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}):L(),E()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{b()}});function E(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
